### ISSUE TITLE
Signature algorithm of "HS256" is not supported. Expected the ID token to be signed with "RS256"

### ISSUE THREAD

**Issue by madison890000** [auth0/auth0-react#130]
# Describe the problem

> Can not get IdToken througth the function getIdTokenClaims, and isAuthenticated always false, if the Application choose the Oauth config JsonWebToken Signature Algorithm to HS256.

Error:
 Signature algorithm of "HS256" is not supported. Expected the ID token to be signed with "RS256"

### What was the expected behavior?

> should support HS256.

**Comment by adamjmcgrath** [comment]
Hi @madison890000 

This library doesn't support HS256 - you're probably hitting this error because your client is configured to use HS256 in your tenant.

Have a look at https://github.com/auth0/auth0-spa-js/blob/7b2ab405b084fb28cc1b050ca0a2c82f050e8ed3/FAQ.md#why-do-i-get-an-invalid-algorithm-error for how to fix

**Comment by madison890000** [comment]
@adamjmcgrath
 thanks! 
I know the reason, I just wanna make sure will the library support HS256 later?

**Comment by stevehobbsdev** [comment]
@madison890000 To answer your question, no this library will not support HS256 in the future. Support relies on the underlying [Auth0 SPA SDK](https://github.com/auth0/auth0-spa-js), and historically we are moving away from HS256 as [RS256 is a more secure option](https://auth0.com/blog/navigating-rs256-and-jwks/#RS256-vs-HS256) as it does not rely on a single shared secret.

Hope that answers your question. What concerns do you have about using RS256?
