### ISSUE TITLE
Email Verification Refresh causes Invalid State

### ISSUE THREAD

**Issue by VED-StuartMorris** [auth0/auth0-react#143]
Hello,

We are using the latest version of auth0-react. We have an Invalid State issue which has been reported to support (00469615) but raising here as the question might relate directly to the repo.

Steps to Reproduce:
- Head to our React SPA > Redirected to Auth0
- Create new account > Email Verification is required
- User directed back to React SPA (we check the error object via useAuth0 hook and display an Email Verification UI
Example URL:
http://localhost:3000/?error=unauthorized&error_description=Please%20verify%20your%20email%20before%20logging%20in&state=TksySzJaazB6b3drdFdhVDFCWlFwVkQyd3lRV2E4a1dzLV9zLkdZRXo0Zg%3D%3D

If the user then refreshes this page they are shown an Invalid State error.  

To be clear, the error object on useAuth0 the first time is Please verify your email..., but when you refresh the error object is then Invalid State.

Is there something we should be doing differently to stop the Invalid State errors from occurring?

```
const { isAuthenticated, error, isLoading, user } = useAuth0();
...

  if (error) {
    return (
      <Theme>
        <>
          ...
                <GenericErrorPage error={error} />
                ...
        </>
      </Theme>
    );
  }
```

There isn't much to the above, we just handle the error Auth0 provides. But we do not want a user to see Invalid State. 

Thanks,

**Comment by adamjmcgrath** [comment]
Hi @VED-StuartMorris 

When login is successful, `onRedirectCallback` is called which removes the state parameter from the url (https://github.com/auth0/auth0-react/blob/master/src/auth0-provider.tsx#L165-L169)

Because there is an error `onRedirectCallback` is not called and the state param is not removed, therefore when you refresh the page with the state param still there, you get "Invalid State", because that old state param is no longer valid (there isn't a corresponding `state` cookie to check it against)

For now, you need to do what `onRedirectCallback` does and [remove the state parameters ](https://github.com/auth0/auth0-react/blob/master/src/auth0-provider.tsx#L165-L169) when you handle the error.

**Comment by VED-StuartMorris** [comment]
Thanks @adamjmcgrath 

Are you suggesting just to change the check like this?
```
const { isAuthenticated, error, isLoading, user } = useAuth0();
...

  if (error) {
    window.history.replaceState({}, document.title);
    return (
      <Theme>
        <>
          ...
                <GenericErrorPage error={error} />
                ...
        </>
      </Theme>
    );
  }
```

As this seems to make no difference.

**Comment by adamjmcgrath** [comment]
Thanks @VED-StuartMorris 

> It might be worth documenting this on the get started.

Yep, will have a think about that
