### ISSUE TITLE
Issues with Parcel bundler

### ISSUE THREAD

**Issue by palfrey** [auth0/auth0-react#160]
### Describe the problem

Trying to build an app with auth0-react and [Parcel](https://parceljs.org/) got me the following warning:
`Could not load existing sourcemap of "../node_modules/@auth0/auth0-react/dist/auth0-react.esm.js"`. Not sure if there's something that needs changing in Parcel config, or if there's a packaging issue from the auth0-react end?

### What was the expected behavior?

No warnings!

### Reproduction

I've got a Typescript project and the root file I'm telling Parcel to build from has the line `import { Auth0Provider, AppState } from '@auth0/auth0-react'`

### Environment

- auth0-react: 1.2.0

**Comment by adamjmcgrath** [comment]
Hi @palfrey 

This is a known issue with using spa-js and Parcel 1.x, caused by https://github.com/parcel-bundler/parcel/issues/2408 

There's a couple of workarounds on https://github.com/auth0/auth0-spa-js/issues/427 namely using parcel with `--no-source-maps` as described in parcel-bundler/parcel#2408 or using `parcel@2`
