### ISSUE TITLE
"Consent Required" 

### ISSUE THREAD

**Issue by acomito** [auth0/auth0-react#186]
- next.js
- "@auth0/auth0-react": "^1.2.0"

I don't think this is related to apollo or next, but here's the code anyway

apollo.js

```
import { setContext } from "@apollo/client/link/context";
import { ApolloClient, ApolloLink, InMemoryCache } from '@apollo/client'
import apolloLogger from 'apollo-link-logger'
import config from '@lib/config'
import { createUploadLink } from 'apollo-upload-client'

const { API_URL } = config

/**
 * Upload link will allow us to do file uploads. It also acts as the HTTPLink.
 */
const uploadLink = createUploadLink({
  uri: `${API_URL}/graphql`,
  headers: {
    'keep-alive': 'true'
  }
})

export const getApolloClient = (getAccessTokenSilently, audience, scope) => {
  const authLink = setContext(async (_, { headers }) => {
    try {
      const token = await getAccessTokenSilently({ audience, scope });

      if (!token) {
        return { headers };
      }
      return {
        headers: {
          ...headers,
          authorization: `Bearer ${token}`,
        },
      };
    } catch (err) {
      console.log({ err })
      return { headers };
    }
  });

  return new ApolloClient({
    ssrMode: typeof window === 'undefined',
    link: ApolloLink.from([authLink, apolloLogger, uploadLink]),
    cache: new InMemoryCache(),
  });
}


```

_app.tsx

```

const AppWithApollo = ({ Component, pageProps }) => {
  const { getAccessTokenSilently } = useAuth0();
  const apolloClient = getApolloClient(getAccessTokenSilently, config.AUTH0_AUDIENCE, config.AUTH0_SCOPE);
  return (
    <ApolloProvider client={apolloClient}>
      <ThemeProvider theme={theme}>
        <Component {...pageProps} />
      </ThemeProvider>
    </ApolloProvider>
  )
}

class MyApp extends App {
  render() {
    const { Component, pageProps } = this.props

    let auth0ProviderConfig = {
       clientId: config.AUTH0_CLIENT_ID,
       domain: config.AUTH0_DOMAIN,
       redirectUri: config.REDIRECT_URI,
       scope: config.AUTH0_SCOPE,
       audience:  config.AUTH0_AUDIENCE,
       cacheLocation: "localstorage",
       useRefreshTokens: true
    }

    return (
      <>
        <Head>
          <link
            href="https://fonts.googleapis.com/css2?family=Roboto:wght@100;300;400;500;700;900&display=swap"
            rel="stylesheet"
          ></link>
          <NewRelic
            licenseKey={NEW_RELIC_LICENSE_KEY}
            applicationID={NEW_RELIC_APPLICATION_ID}
          />
        </Head>
        <GlobalStyle />
       <Auth0Provider {...auth0ProviderConfig}>
          <AppWithApollo {...this.props} />
        </Auth0Provider>
      </>
    )
  }
}
```

Ok, so some more observations

- When I don't pass Auth0Provider an audience, getAccessTokenSilently doesn't throw and error, but it just seems to give back what looks like an ID (it's definitely not a token, way too short).
- When I do pass in a audience, I get the "Consent Required" error from getAccessTokenSilently
- This is running on localhost
- To find the audience, I'm going to Applications > APIs and taking the "Auth0 Management API" and taking the audience from there
- Going through our Users, I don't see any of them have permissions set (or anything about consent.)
- We had auth0 setup another way (through a proxy that would add the token) but we want to set it up a little more "normal" without the middle man api endpoint. The reason I mention this, is that it was working doing this but is now not working with the new setup.

Does anyone have any ideas what settings I should be looking at in auth0? I do see a "consent" screen when I signup as a user, and I say yes, but it still says the user is "consent required"

I'm running out of ideas of things to try...I've spent more time trying to get auth0 working then it would have taken to built auth from scratch lol

**Comment by stevehobbsdev** [comment]
@acomito It's not clear from your issue as to what you need help with, but let me try to clarify a couple of things.

> When I don't pass Auth0Provider an audience, getAccessTokenSilently doesn't throw and error, but it just seems to give back what looks like an ID

That's expected - if you don't pass an audience it effectively indicates that you will not be calling any APIs, so Auth0 returns an opaque token. By specifying an audience, you will get an access token in JWT format, which can then be sent to an API and inspected.

> When I do pass in a audience, I get the "Consent Required" error from getAccessTokenSilently

That's expected if your user has not given consent through the login flow. Normally if you just have the one audience, you would specify it in your Auth0 config so that it is sent to the `/authorize` endpoint when you log in. There the user has a chance to consent. I can't see from your code where the login is being kicked off (by calling `loginWithRedirect`) but normally that's where it would happen.

There is something else too - [consent is **always** required when running on localhost](https://auth0.com/docs/authorization/user-consent-and-third-party-applications#skip-consent-for-first-party-applications), regardless of the "Skip consent for first-party apps" setting that is available (and turned on by default) in your Auth0 tenant settings.

Does this help?

**Comment by acomito** [comment]
Thanks @stevehobbsdev 

Does this project work with nextjs (SSR)?

If not, what's the best practice for nextjs + apollo+ auth0?

**Comment by frederikprijck** [comment]
@acomito you might want to check out https://github.com/auth0/nextjs-auth0/tree/beta, the team released the beta yesterday!

**Comment by acomito** [comment]
fantastic!

Closing this for now as to not clog up your issues
