### ISSUE TITLE
Gatsby Example

### ISSUE THREAD

**Issue by Lowkase** [auth0/auth0-react#197]
### Describe the problem
The package.json file was creating errors on "npm install", "npm update". I need to copy over valid entries from an existing gatsby project to get npm to install correctly.

The code in gatsby-browser.js works fine... BUT... it needs to be repeated in the gatsby-ssr.js file for the LOGIN button to work properly. Without repeating the gatsby-browser.js code in gatsby-ssr.js the LOGIN button click produces a browser error.

### What was the expected behavior?
Grab the Gatsby Example, run npm install then gatsby develop to run the sample app.
Use the login button without error.

### Reproduction
- Grab the Gatsby example code from the repo
- Run 'npm install' or 'npm update' ---- npm ERRORS
-  If you fix the package.json file using a current gatsby package.json file... then....
- gatsby develop and click on the LOGIN button ---- browser error

### Environment
- **Version of `auth0-react` used:**
- ^1.2.0 (as per the code downloaded from the repo)
- **Which browsers have you tested in?**
- Chrome
- **Which framework are you using, if applicable (Angular, React, etc):**
- Gatsby
- **Other modules/plugins/libraries that might be involved:**
- None

**Comment by adamjmcgrath** [comment]
Hi @Lowkase - I just tested the gatsby example app and it built correctly and I was able to login successfully

Also, our CI ran a successful smoke test (which includes login) with that Gatsby app yesterday:

![image](https://user-images.githubusercontent.com/1299658/107761186-dbdde480-6d22-11eb-8cac-2a5beb40131d.png)

A couple of things you could try to get it working:

- delete `examples/gatsby-app/node_modules/` and the root `node_modules/`
- delete `examples/gatsby-app/node_modules/package-lock.json` if you have one (we don't use package locks in the example apps because the mess with locally linked packages)
- from the root of the project run:
  - `npm install`
  - `npm build` the gatsby app points to the local version of `auth0-react` so you need to build it locally
  - `npm run install:examples` this installs the gatsby app without a `package-lock.json`
  - `npm run start:gatsby`
 
If you're still seeing errors when trying to login, share the details of the error and I'll take a look

**Comment by adamjmcgrath** [comment]
@Lowkase - closing due to innactivity.

Ping me if you have any other questions or you'd like me to reopen this
