### ISSUE TITLE
Can't logout

### ISSUE THREAD

**Issue by uluhonolulu** [auth0/auth0-react#207]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

After calling `logout` with `localOnly: true`, the user is logged back in after a few moments.

### What was the expected behavior?

The user should stay logged out.

### Reproduction

This is my setup:
```
				<Auth0Provider
					domain="flyent.eu.auth0.com"
					clientId="3E-8GqIgvil8qfMr25U5nEaEBK3uNPfB"
					redirectUri={window.location.origin}
					useRefreshTokens={true}
					cacheLocation="localstorage"
					onRedirectCallback={appState => historyContainer.current.push(appState.returnTo)}
				>
```

This is how I login:
```
			await loginWithRedirect({
				appState: {returnTo: returnUrl},
				display: 'page',
				screen_hint: "signup",
				redirect_uri: `${window.location.origin}/Students/Start`,
				max_age: 7776000
			})
```

And I logout using `logout({localOnly: true});` (I don't want to redirect).

I tried to debug the issue, and this is what I found: Auth0 Provider calls `client.checkSession()` (https://github.com/auth0/auth0-react/blob/8f177539164aff8992d9dce3ace6e3acb8b16beb/src/auth0-provider.tsx#L222), which in turn calls `getTokenSilently` -> `_getTokenSilently` -> `_getTokenFromIFrame`. It looks like the local logout can do a local cleanup but can't prevent from getting the auth codez from an iframe.

My guess is that if only we could pass the `useRefreshTokens` option to the SPA code, it wouldn't call  `_getTokenFromIFrame`, but I haven't tried that.

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** 1.1.0
- **Which browsers have you tested in?** Chrome
- **Which framework are you using, if applicable (Angular, React, etc):** none
- **Other modules/plugins/libraries that might be involved:** not likely

**Comment by adamjmcgrath** [comment]
Hi @uluhonolulu - thanks for raising this

> And I logout using logout({localOnly: true}); (I don't want to redirect).

`localOnly: true` will not log you out of `flyent.eu.auth0.com`. It just logs you out of the local application, by removing the in memory user details and the `auth0.is.authenticated` cookie.

The `auth0.is.authenticated` cookie is the cookie that tells `checkSession` to try and log you in to `flyent.eu.auth0.com` via the iframe (it even does this as a fall back if you're using refresh tokens) when the page loads.

Since you've logged out locally, you should not have the `auth0.is.authenticated` cookie, so `checkSession` wont log you back in (I've just verified this in the playground app).

> After calling logout with localOnly: true, the user is logged back in after a few moments.

I suspect that what is happening is that, after a few moments, your code is calling `getAccessTokenSilently` which will check `flyent.eu.auth0.com` for a session and log you back in. `getAccessTokenSilently` doesn't check the `auth0.is.authenticated` and falls back to the iframe regardless of your `useRefreshTokens` settings.

If you really want to do local logout, and log your user out of your app but keep them logged in to `flyent.eu.auth0.com`, you'll need to check for the local logged in state before calling `getAccessTokenSilently`, eg:

```js
if (isAuthenticated) {
  await getAccessTokenSilently();
}
```

**Comment by uluhonolulu** [comment]
Hi @adamjmcgrath, thanks for looking into this!

I'm not calling `getAccessTokenSilently` anywhere in my code. And I'm pretty sure it's called from `checkSession` (https://github.com/auth0/auth0-spa-js/blob/be9e9d723e847ddc8414140426eb417bce4590aa/src/Auth0Client.ts#L591), as I wrote in my original post. When the code calls `checkSession`, the `auth0.is.authenticated` cookie is not present, however, it's there when the call is finished.

I don't care about being logged in or out from `flyent.eu.auth0.com`, but I would really prefer to avoid redirection. SPAs are about not having to reload your pages, after all.

Actually, do you think I should have opened the issue on the auth0-spa-js repository instead?

**Comment by adamjmcgrath** [comment]
Hi @uluhonolulu - can you update to the latest `auth0-react`?

It should include https://github.com/auth0/auth0-spa-js/pull/613 - which I believe will fix your issue

**Comment by uluhonolulu** [comment]
Hi @adamjmcgrath,

Upgrading fixed the issue, thank you for looking into this!
