### ISSUE TITLE
Option to pass Auth0Client instance into Provider

### ISSUE THREAD

**Issue by mmakarin** [auth0/auth0-react#212]
### Describe the problem you'd like to have solved

Right now you can't access Auth0Client instance outside of React.
Valid use case for this is calling `logout()` from redux-saga or axios (in response to 403 from backend for example).
Another use case is storing token in redux and accessing it in redux-saga/whatever without hacks like this:
```
  useAsyncEffect(
      async isMounted => {
        const token = await getAccessTokenSilently();      
  
        if (!isMounted) {
          return;
        }
  
        dispatch(updateAuthToken(token));
      },
      [getAccessTokenSilently]
    );
```

> A clear and concise description of what you want to happen.
```
    const client = new Auth0Client(...);

    render(
        <Auth0Provider client={auth0client}>...<Auth0Provider />
    );

    // Outside of component
    client.logout();
```

**Comment by adamjmcgrath** [comment]
Hi @mmakarin - thanks for raising this

We've decided not to implement this feature, and discussed some reasons and workarounds in #187, #134, #97, #67 and #37

**Comment by jaitaiwan** [comment]
Hi @adamjmcgrath,

I've gone through the issues and the suggested work-arounds and they seem to come under two categories:

- Refactor your app so that the need for the auth0 client is subordinate to where it's initialised so that you can make use of react's contexts
- Refactor any code that needs the client into a function to receive the client as an argument to it

The two cons with these approaches were somewhat hinted at in one of the issues:

 - It forces any setups that happen reliant on the auth0 client to be recreated therefore meaning it's no longer cached
 - In cases where you're doing something like using the auth0 client in an apollo subscription, the code becomes more needlessly complex because subscriptions has to be setup within a component somewhere rather than nicely filed away in a separate set of react-less functions.
 
You mentioned that your major reason for not supporting the Auth0Provider receiving a fully-setup client is that there may be differences in the client provided to the provider and what the provider expects to be there. Frankly this seems like a poor reason as many other libraries do this exact thing (apollo for example) and it's par-for-the-course and usually handled by requiring particular versions in package.json files.

The fact that there has been a couple PRs and 4 or so issues on this, and the examples being somewhat convoluted to me (referencing examples others have provided to try and get around the limitations of the library and having to post links to large files) highlights the need for it, and the cognitive dissonance the community has experienced when not having that option available to them when it is available in other comparable libraries.

Now that we're nearly a year down the road, is there a chance this gets revisited?

**Comment by adamjmcgrath** [comment]
Hi @jaitaiwan - thanks for your question. The advice remains the same.

See https://gist.github.com/adamjmcgrath/0ed6a04047aad16506ca24d85f1b2a5c for more details and workarounds to your problem.
