### ISSUE TITLE
Programmatically log in a user for end to end testing documentation 

### ISSUE THREAD

**Issue by charklewis** [auth0/auth0-react#234]
### Describe the problem you'd like to have solved

I am trying to programmatically log in a user using this SDK for end to end tests, and can't seem to get this working. There is limited to no documentation on how to achieve this. 

### Describe the ideal solution

Clear documentation on how to achieve this.

### Alternatives and current work-arounds

 There is [documentation that Cypress provides](https://docs.cypress.io/guides/testing-strategies/auth0-authentication#Custom-Command-for-Auth0-Authentication), and also some that [Auth0 provides](https://auth0.com/blog/cypress-write-automated-tests-to-validate-web-applications/#The-Test-Pyramid-and-Importance-of-E2E-tests) but none match the approach provided by the [official documentation given by Auth0](https://auth0.com/docs/libraries/auth0-react) for this SDK. 

### Additional context

I have a stack overflow post that explains this problem in more detail - https://stackoverflow.com/questions/67222522/auth0-authentication-with-cypress.

**Comment by adamjmcgrath** [comment]
Hi @charklewis - thanks for raising this

We don't provide specific documentation for using auth0-react with Cypress.

The [Cypress documenation](https://docs.cypress.io/guides/testing-strategies/auth0-authentication#Custom-Command-for-Auth0-Authentication) you pointed to uses auth0-react - so should work for this SDK.

Is there a specific issue with this SDK that's stopping it from working for you?

**Comment by charklewis** [comment]
The cypress documentation alludes to setting up a node service to authenticate the request, whereas I am just using the LockUI to handle everything. 

I have created a very simple repo to demonstrate how adding the required to local storage doesn't work. I feel like there is another step I have to take in order for the SDK to register that there is a user signed in. 

https://github.com/charklewis/auth0-cypress

Can you see anything obvious that I am missing?

**Comment by adamjmcgrath** [comment]
Hi @charklewis - thanks for sharing that example app

I was able to login successfully and that test passes for me:
![image](https://user-images.githubusercontent.com/1299658/116701486-db6af680-a9bf-11eb-9fff-779a9a5d1687.png)

The tricky thing is making sure the `localStorage` key you are setting in cypress https://github.com/charklewis/auth0-cypress/blob/master/cypress/support/commands.js#L29 matches the one that the spa js (used by auth0-react) looks for https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L449-L453

I suspect the issue was that you had specified `useRefreshToken` in auth0 react, which means auth0-react will now look for an item in localStorage with a cache key with the scope `openid profile email offline_access`. So the cache key for the artifact you set in localStorage from cypress should match that and include the `offline_access` in the scope, see https://github.com/adamjmcgrath/auth0-cypress/blob/master/cypress/support/commands.js#L12

> The cypress documentation alludes to setting up a node service to authenticate the request, whereas I am just using the LockUI to handle everything.

This is just for setting up an External API to test against, if you already have one of these - or you're not accessing an external api, you don't need this.

I have some tips for how to debug issues like this here https://github.com/adamjmcgrath/cypress-spa-example/issues/2#issuecomment-765583180

**Comment by charklewis** [comment]
Ah thank you so much for this investigation! You were 100% correct, the `refreshTokens` were the issue here. After adding the updated scopes it work. 

I was going to post an answer to my stack overflow post, however it currently has a bounty on it so I'll leave it open for you incase you wanted to leave an answer there (I can then award you the bounty 😉).

https://stackoverflow.com/questions/67222522/auth0-authentication-with-cypress
