### ISSUE TITLE
MockedAuth0Provider for testing in jest

### ISSUE THREAD

**Issue by kcarra** [auth0/auth0-react#248]
### MockedAuth0Provider for testing 
Hopefully this is an appropriate place to post this, but I've been banging my head against the wall for a few days now trying to find the best way to test my react app which is wrapped in the `Auth0Provider` The problem seems to be with the `Auth0Client` and some of the checks it does before initializing, mainly around validating that `window.crypto` exists. I've tried to mock out the `Auth0Client` similar to what is done in this repo in `__mocks__/@auth0` however I still haven't been able to get around this error. `Uncaught [Error: For security reasons, window.crypto is required to run auth0-spa-js.]`   In my tests i have a custom `render` function that imports `import { Auth0Provider } from "@auth0/auth0-react";` and returns:
```
 return <Auth0Provider clientId="__test_client_id__" domain="__test_domain__">
              <Provider store={store}>
                <MockedProvider mocks={[getUserMock, ...mocks]} addTypename={false}>
                  <UserProvider>{children}</UserProvider>
                </MockedProvider>
              </Provider>
            </Auth0Provider>
```
I've seen a few suggestions of people recommending to set a global `window.crypto` in `setUpTests.js`  but this still seems like it could be avoided with a mocked provider.

### Describe the ideal solution
Have a `MockedAuth0Provider` that doesn't do the check for `window.crypto` or provide a way to pass a mocked `Auth0Client` as a prop to the `Auth0Provider`.

## Alternatives and current work-arounds
The only current work around that I have seen is to define a crypto property on the window object.

I'm a React and Jest novice so if this isn't a valid request I apologize, but I've exhausted all the options that I could find to solve this problem. Any tips on how to get the `Auth0Provider` mocked out properly would be greatly appreciated.

Thanks

**Comment by adamjmcgrath** [comment]
Hi @kcarra

You can mock the Auth0Provider using `jest.mock`, eg

```js
import React from 'react';
import ReactDOM from 'react-dom';
import { Auth0Provider } from '@auth0/auth0-react';

jest.mock('@auth0/auth0-react', () => ({ Auth0Provider: ({ children }) => '<div>{children}</div>' }));

it('renders without crashing', () => {
  const div = document.createElement('div');
  ReactDOM.render(<Auth0Provider />, div);
});
```

**Comment by kcarra** [comment]
Thank you very much @adamjmcgrath! This solved my problem, I ended up putting all the mocks for auth0 in the setupTests.js file
```
import "@testing-library/jest-dom/extend-expect";

jest.mock('@auth0/auth0-react', () => ({
  Auth0Provider: ({ children }) => children,
  withAuthenticationRequired: ((component, _) => component),
  useAuth0: () => {
    return {
      isLoading: false,
      user: { sub: "foobar" },
      isAuthenticated: true,
      loginWithRedirect: jest.fn()
    }
  }
}));
```

**Comment by jgoux** [comment]
@adamjmcgrath How would you approach the exact same issue but in the context of Storybook? We need to mock the Auth0Provider and the useAuth0 hook in order to inject a fake connected user inside our stories. Right now we're unsure about the right way of doing it.

**Comment by adamjmcgrath** [comment]
Hi @jgoux - I'm not familiar with Storybook, but it looks like you can mock providers in a similar way here https://storybook.js.org/docs/react/workflows/build-pages-with-storybook#mocking-providers

**Comment by jgoux** [comment]
@adamjmcgrath The issue is that there is nothing to mock with the `Auth0Provider` as it builds the client internally. Mocking providers is working only when those contexts are used as a transport mecanism and the client is injected externally (like redux's store, or apollo's client).
I'll try to make it works using the import mocking and webpack aliases : https://storybook.js.org/docs/react/workflows/build-pages-with-storybook#mocking-imports

**Comment by nirvdrum** [comment]
I think it'd be helpful if Auth0 shipped with a mock provider much like Apollo does. Using `jest.mock` in every test file is a lot of duplication. As far as I can tell, there's no way in jest to push that out to a helper method that gets called. Moreover, due to the way Jest hoists mocks, I can't see a way to test two different mocked responses within the same test file. Having to split component tests out into multiple files based on auth state is going to be rather annoying.

That leaves @kcarra's suggestion of using _setupTests.ts_. That addresses the duplication issue, but only works for a single auth state. Someone better versed with Jest can likely find a way to conditionally change the response based on some closed over state with external control. That might require running tests with `--runInBand`.

Having an official solution with accompanying documentation would be very helpful.

**Comment by RanSolo** [comment]
I'm doing this a little different, using auth0-nextjs, but it doesn't  which feels a little cleaner to me.  
Create client.ts file in mocks, jest looks here automatically for mocked modules.
 
<img width="207" alt="image" src="https://github.com/auth0/auth0-react/assets/6284142/8e654b4c-e4ec-4856-aca6-2d1d7da44bd7">

inside __mocks__/@auth0/nextjs-auth0/client.tsx 
```
import { getAuth0User } from '@mocks/userMock'; // just a mocked user object

export const customUseUser = jest.fn(() => getAuth0User);
export const customAuth0Provider = ({ children }: { children: unknown }) => (
  <div>{children}</div>
);
export * from '@auth0/nextjs-auth0/client';
export { customUseUser as useUser, customAuth0Provider as UserProvider };
```

Then in test-utils import UserProvider as usual.
```import { UserProvider } from '@auth0/nextjs-auth0/client';```
