### ISSUE TITLE
Cannot retry login after access denied with email domain whitelist

### ISSUE THREAD

**Issue by mrosendin** [auth0/auth0-react#256]
### Describe the problem

I've set up a domain whitelist rule (code below). After attempting to login with an email from a domain that is not allowed using the Google login provider, I cannot retry login. Subsequent calls to `loginWithRedirect()` does not redirect me to Auth0.

After clearing the URL search params, calls to `loginWithRedirect()` update the params with a new state.

`http://localhost:3000/?error=unauthorized&error_description=Access%20denied.&state=dG85eWpMVC1HMi5fVmdaa1RjX2N5N2g3b1c2SGYucXdxeXpieTlTc0lELg%3D%3D`

I have to clear Auth0 site cookies in Chrome for the login flow to work again:

Settings > Privacy and security > Clear browsing data > See all cookies and site data > myauth0domain.com > Remove all

Here's the email domain whitelist rule:

```javascript
function emailDomainWhitelist(user, context, callback) {
  // Access should only be granted to verified users.
  if (!user.email || !user.email_verified) {
    return callback(new UnauthorizedError('Access denied.'));
  }

  if (context.clientID === "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx") {
    const whitelist = ['mydomain.com']; // authorized domains

    const userHasAccess = whitelist.some(function (domain) {
      const emailSplit = user.email.split('@');
      return emailSplit[emailSplit.length - 1].toLowerCase() === domain;
    });

    if (!userHasAccess) {
      return callback(new UnauthorizedError('Access denied.'));
    } 
  }

  return callback(null, user, context);
}
```

### What was the expected behavior?

I'm expecting to be redirected to Auth0 so I can login with a whitelisted email domain.

### Reproduction

- Step 1. Setup email whitelist rule as shown above
- Step 2. Attempt to login with an invalid email
- Step 3. Retry `loginWithRedirect`

I've reproduced this with the React SDK Playground using the same steps as above. No modifications to the app need to be made, only the rule needs to be added in the Auth0 dashboard.

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** 1.5.0
- **Which browsers have you tested in?** Chrome
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:** n/a

**Comment by frederikprijck** [comment]
Hi @mrosendin ,

Can you verify there is no redirect happening by looking at the browser's network tab?
My assumption is that there is a redirect happening, but it instantly redirects back to the application because the current user is already authenticated with Auth0, that is how Auth0's Universal Login Page works by default.

You should be able to use `prompt: 'login'` to enforce Auth0 to show the login page regardless of already being authenticated.

```
loginWithRedirect({prompt: 'login'})
```

I do believe doing this by default will end up in a weird user experience, so if possible I would only use `prompt: 'login'` when you have detected an Unautherized error in the client, using a `Sign in as a different user` kind of button. But that is ofcourse up to you.

Let me know if that doesn't work?

**Comment by mrosendin** [comment]
@frederikprijck your suggestion

```
loginWithRedirect({prompt: 'login'})
```

fixed it! TYSM!

**Comment by frederikprijck** [comment]
Glad to hear that, happy to help!
