### ISSUE TITLE
Compatibility with other js sdk

### ISSUE THREAD

**Issue by gabsn** [auth0/auth0-react#258]
It is a shame that the different js sdks are not compatibles between each others. I would need to use the different sdks in conjunctions for my custom needs but I need to duplicate a lot of code 😢

For example, to instantiate the client:

- `@auth0/auth0-react`
```js
<Auth0Provider
    domain="shopidog.eu.auth0.com"
    clientId="TaAOtuz41cNXYFATTABqt3lYnFIW7mXc"
    redirectUri={window.location.origin}
  >
```
- `@auth0/auth0-spa-js`
```js
const auth0 = await createAuth0Client({
  domain: 'shopidog.eu.auth0.com',
  client_id: 'TaAOtuz41cNXYFATTABqt3lYnFIW7mXc'
});
```
- `@auth0/auth0-nextjs`
```js
initAuth0({
  secret: process.env.SESSION_COOKIE_SECRET,
  issuerBaseURL: process.env.NEXT_PUBLIC_AUTH0_DOMAIN,
  baseURL: process.env.NEXT_PUBLIC_BASE_URL,
  clientID: process.env.NEXT_PUBLIC_AUTH0_CLIENT_ID,
  clientSecret: process.env.AUTH0_CLIENT_SECRET,
  routes: {
    callback:
      process.env.NEXT_PUBLIC_REDIRECT_URI ||
      "http://localhost:3000/api/callback",
    postLogoutRedirect:
      process.env.NEXT_PUBLIC_POST_LOGOUT_REDIRECT_URI ||
      "http://localhost:3000",
  },
  authorizationParams: {
    response_type: "code",
    scope: process.env.NEXT_PUBLIC_AUTH0_SCOPE,
  },
  session: {
    absoluteDuration: parseInt(process.env.SESSION_COOKIE_LIFETIME || "7200"),
  },
});
```

**Comment by adamjmcgrath** [comment]
Hey @gabsn 

> I would need to use the different sdks in conjunctions for my custom needs 

Could you tell me more about your use case? I think it would be difficult to make the SDKs much more compatible because they are used in such different contexts, eg

- `auth0-react` is a frontend SDK provides auth through the React context api, so should be instantiated in a JSX provider (`<Auth0Provider>`), SPA-JS doesn't assume you have JSX so is instantiated with Vanilla JS.
- `nextjs-auth0` is a server side SDK, so is instantiated in a node environment, it requires secrets which can't be used on the front end so uses environment variables.

We tend to go for styles and concepts that are familiar with the platform (eg Vanilla JS, React and Next) rather than focus on making the SDKs conform to each other.

I feel you pain on things like the casing of `clientId` - there's a historical reason why auth0-react is `clientId` and SPA JS is `client_id` that we'll fix on the next Major update of SPA JS and `nextjs-auth0`'s `clientID` is consistent with our other Node middleware SDKs

**Comment by ilyaulyanov** [comment]
@adamjmcgrath It's totally understandable that styles and concepts change, depending on the platform. When using multiple SDKs in the same environment, on the same domain (e.g. app A uses React SDK, app B uses SPA JS SDK, and an Express server loads either A or B depending on a URL) can they recognize & accept tokens stored in `localstorage` by either SDK, after logging in? If not, user has to log in again after logging into app A, and then going to a route loading app B, is that correct?

**Comment by adamjmcgrath** [comment]
Hey @ilyaulyanov 

> When using multiple SDKs in the same environment, on the same domain (e.g. app A uses React SDK, app B uses SPA JS SDK, and an Express server loads either A or B depending on a URL) can they recognize & accept tokens stored in localstorage by either SDK, after logging in?

Yes - auth0-react is just a thin wrapper around a SPA JS client so effectively app A and app B are both using SPA JS

**Comment by adamjmcgrath** [comment]
@gabsn - closing this as I think I've answered your question, feel free to ping me if you'd like me to reopen it

**Comment by gabsn** [comment]
Yep thanks, fully understand!
