### ISSUE TITLE
User doesn't stay logged in when using Incognito 

### ISSUE THREAD

**Issue by Srkl** [auth0/auth0-react#261]
Hello everyone, 

After spending many hours chasing a strange redirect loop in my application, I've identified that the problem is caused by the Incognito window. 

The user credentials are stored in the local cache when the application is being accessed using an Incognito window. This issue confused me a lot and made me lose many hours debugging. My application was working normally in my user in a normal window, but it was always redirecting back to the home using my test account in incognito mode.

I can see in the Auth logs the following error when I try to access a ProtectedRoute in an Incognito window: 

```
Type: Failed Silent Auth
Description: Login required
```

I created one of the Auth0 React start projects and the problem is very easy to replicate. 

```
import React from 'react';
import ReactDOM from 'react-dom';
import './index.css';
import App from './App';
import { Auth0Provider } from "@auth0/auth0-react";
import { createBrowserHistory } from "history";

const history = createBrowserHistory();

const onRedirectCallback = (appState) => {
  history.replace(appState?.returnTo || window.location.pathname);
};

ReactDOM.render(
  <Auth0Provider
    domain="<DOMAIN>"
    clientId="<CLIENT_ID>"
    redirectUri={window.location.origin}
    audience="<AUDIENCE>"
    onRedirectCallback={onRedirectCallback} 
    useRefreshTokens={true}
  >
    <App />
  </Auth0Provider>,
  document.getElementById("root")
);
```

```
export default function App() {
  return (
    <Router history={history}>
      <Switch>
        <Route exact path="/" component={Home} />
        <ProtectedRoute path="/profile" component={Profile} />
      </Switch>
    </Router>
  );
};
```

```
const ProtectedRoute = ({ component, ...args }) => (
  <Route
    component={withAuthenticationRequired(component, {
      onRedirecting: () => <Loading />,
    })}
    {...args}
  />
);
```

**Comment by stevehobbsdev** [comment]
👋🏻  [Third-party cookies are blocked by default in Incognito mode](https://venturebeat.com/2020/05/19/google-chrome-83/), which are required for silent authentication to work (otherwise Auth0 Server doesn't know who is logged in, because it can't read the session cookie).

We have a write-up of this scenario on [our community forums](https://community.auth0.com/t/why-is-authentication-lost-after-refreshing-my-single-page-application/56276), point 2) is relevant here. Let me know if that helps to clear things up for you.
