### ISSUE TITLE
redirect_uri property ignored on loginWithRedirect

### ISSUE THREAD

**Issue by simonwatt** [auth0/auth0-react#294]
### Describe the problem

> Provide a clear and concise description of the issue

When calling  loginWithRedirect() the redirect_uri option is ignored when passed. For example calling:
loginWithRedirect({ redirect_uri: 'http://localhost:3000/aftersignin' });  will never have any redirect_uri param passed to the authorize endpoint (as monitored in Chrome network tab).. As a result, after sign in the user is not redirected to where they should go.  Other options, as per the documentation, are handled as expected, e.g "screen_hint: 'signup'".

### What was the expected behavior?
> Tell us about the behavior you expected to see

After sign in user should be redirected to the value supplied in redirect_uri (note, I have allowed the supplied value in the allowed callbacks URLs on Auth0 dashboard).

I'm using @auth0/auth0-react@1.6.0, and @auth0/auth0-spa-js@1.17.0

Also note, when providing the redirectUri property on the <Auth0Provider redirectUri='http://localhost:3000/aftersignin' .../> it works as expected, just not the redirect_uri on the loginWithRedirect options. I can provide more steps to reproduce if that isn't enough. Let me know.

**Comment by frederikprijck** [comment]
Hey @simonwatt ,

With this SDK, you're expected to use `redirectUri` when calling `loginWithRedirect`, not `redirect_uri`. See: https://auth0.github.io/auth0-react/interfaces/auth0_context.redirectloginoptions.html#redirecturi

So in your case, you should use:

```
loginWithRedirect({ redirectUri: 'http://localhost:3000/aftersignin' }); 
```

**Comment by simonwatt** [comment]
Thanks, not on my dev computer right now but will give it a try soon.

I'm sure documentation I read was using redirect_uri, but maybe I was looking in the wrong place, as the one you linked to does indeed have redirectUri.

**Comment by stevehobbsdev** [comment]
This is an unfortunate byproduct of having properties that are native to the SDK and those that are just params that we pass through to the hosted login page. We'd prefer to use a camel case naming convention in the SDK because that's what's natural for JavaScript but using snake case is more natural for URL params as used by the login page. We could map them but it doesn't scale given the amount of parameters (plus custom ones), plus you'd end up with being able to pass `screenHint` as well as `screen_hint`, which makes the API confusing.

We do have a slight gap here in that `auth0-react` (and `auth0-angular`) will map properties like `redirectUri` to `redirect_uri` for the underlying SDK ([auth0-spa-js](https://github.com/auth0/auth0-spa-js)) but we aim to close this gap in time by making the properties camel case there too.

I think we should continue to do our best to enable discoverability of the accepted parameters in code tools / autocomplete as well as surface them in our docs.

**Comment by simonwatt** [comment]
Okay, that makes sense, thanks for the detailed explanation.
