### ISSUE TITLE
Refresh tokens no longer work in Safari 15 to bypass ITP 

### ISSUE THREAD

**Issue by mirshko** [auth0/auth0-react#299]
### Describe the problem

It seems Safari it blocking `getAccessTokenSilently` even when using `useRefreshTokens` and `cacheLocation="localstorage"` on the `Auth0Provider` in Next.js running in SPA Mode.

This seems to also cause an infinite redirect loop when navigating to a page that uses the protected Route HOC.

### What was the expected behavior?

Safari should allow the iframe-based silent login method.

### Reproduction

Next.js `_app` 

```tsx
<Auth0Provider
      domain={"..."}
      clientId={"..."}
      redirectUri={"http://localhost:3000/"}
      useRefreshTokens
      cacheLocation="localstorage"
      onRedirectCallback={(appState) =>
        Router.replace(appState?.returnTo || "/")
      } >
      <Component />
 </Auth0Provider>
 ```

have a fetcher function that uses `getAccessTokenSilently` that runs on the user logging in.

```ts
import { GetTokenSilentlyOptions, useAuth0 } from "@auth0/auth0-react";
import ky from "ky";
import useSWR from "swr";

type GetAccessTokenSilently = (
  options?: GetTokenSilentlyOptions | undefined
) => Promise<string>;

function fetchWithRequestAccessToken<T>(
  getAccessTokenSilently: GetAccessTokenSilently
) {
  return async (url: string) => {
    const accessToken = await getAccessTokenSilently({
      audience: "...",
      scope: "openid profile email",
    });

    const data = await ky
      .get(url, {
        prefixUrl: "...",
        headers: {
          Authorization: `Bearer ${accessToken}`,
          Accept: "application/json",
        },
      })
      .json<T>();

    console.log(data);

    return data;
  };
}

export default function useAPI<T>(url: string) {
  const { isAuthenticated, isLoading, getAccessTokenSilently } = useAuth0();

  const shouldFetch = !isLoading || isAuthenticated || typeof url === "string";

  console.log({ shouldFetch });

  return useSWR<T>(
    shouldFetch ? [url] : null,
    fetchWithRequestAccessToken<T>(getAccessTokenSilently),
    {
      shouldRetryOnError: false,
    }
  );
}
```

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** 1.8.0
- **Which browsers have you tested in?** Safari (works right in Chrome & Firefox)
- **Which framework are you using, if applicable (Angular, React, etc):** Next.js 12.0.2
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by frederikprijck** [comment]
Hi,

It looks like you are using
```
<Auth0Provider
      domain={"..."}
      clientId={"..."}
      redirectUri={"http://localhost:3000/"}
      useRefreshTokens
      cacheLocation="localstorage"
      onRedirectCallback={(appState) =>
        Router.replace(appState?.returnTo || "/")
      } >
      <Component />
 </Auth0Provider>
```
However, I believe you should explicitly set `useRefreshTokens` to true in order for the SDK to use Refresh Tokens.

> Safari should allow the iframe-based silent login method.

Safari will not allow the iframe based login method unless you use Custom Domains. You can also use refresh tokens, which wont use the iframe method (when a refresh token is available), see https://github.com/auth0/auth0-react/blob/master/FAQ.md#1-user-is-not-logged-in-after-page-refresh

Could you try if the above changes (use `useRefreshTokens="true" instead of just `useRefreshTokens` works ?

**Comment by mirshko** [comment]
I tried with `useRefreshTokens={true}` which is essentially the same thing as `useRefreshTokens`, it still doesn't work though. 

Even with this set it does still seem to inject two iframes into the DOM at login, this could have something to do with immediately calling `getAccessTokenSilently` once the user logs in to get some data though?

**Comment by frederikprijck** [comment]
Yes that could be related. The thing is that `getAccessTokenSilently` will only use Refresh Tokens when available, if not then it will fallback to an iframe which will fail in Safari or any browser that block third party cookies, unless u use custom domains.

The idea would be to catch the LOGIN_REQUIRED error from `getAccessTokenSilently` and call `loginWithRedirect` in that case, ensuring you have an interactive login flow. Once that is done, `getAccessTokenSilently` will use the refresh token.

> this could have something to do with immediately calling getAccessTokenSilently once the user logs in to get some data though?

You also want to ensure u dont call `getAcccessTokenSilently` before the SDK has retrieved the Tokens, which u can do by checking the isLoading, however you are using `const shouldFetch = !isLoading || isAuthenticated || typeof url === "string";`, so whenever url is a string, you bypass that check and might be doing the call before the SDK has done exchanging the code for a token.

**Comment by mirshko** [comment]
Okay I just changed all fetching logic that might called `getAccessTokenSilently` with `const shouldFetch = !isLoading && isAuthenticated && typeof url === "string"`

To make sure its done loading. 

However it still seems to have issues, when removing any calls to this function and using the `refreshTokens` and `cache` things Safari does work across refreshes of the browser. It just seems there is something up with the `getAccessTokenSilently`

I have the refresh token rotation enabled in the tenant and the leeway of 3 seconds.

**Comment by frederikprijck** [comment]
> However it still seems to have issues, when removing any calls to this function and using the refreshTokens and cache things Safari does work across refreshes of the browser. It just seems there is something up with the getAccessTokenSilently

On page refresh, our SDK should be using `getAccessTokenSilently` internally itself so I am not sure what is going on.

At this point I guess it might be a bit easier to troubleshoot if you could provide us with a small example to run and debug ourselves. Would that be possible?

**Comment by mirshko** [comment]
Reproduction Repo: https://github.com/mirshko/auth0-react-safari-bug
Reproduction Deploy: https://auth0-react-safari-bug.vercel.app

**Comment by frederikprijck** [comment]
> Little note, it seems if you request an access token already by setting the audience and scope params on the Provider then it does seem to use the refresh token, that's the only way I was able to get it to work.

Yeah that is most likely the reason. You need to go through an interactive flow for the **Audience** and **Scopes** first. In this example, I don't believe scopes is the issue **but audience is.**

What happens when u call getAccessTokenSilently is that it uses Audience and Scopes to find a token in the cache (memory or local storage).
The default audience is empty, but the default scope are the same as you are using.

As you are not overriding the audience or scope on the AuthProvider, it will be using those values for when calling `loginWithRedirect`, which will result in a token without an audience and for scopes `openid profile email`.

A bit later, you use the following code:

```
const accessToken = await getAccessTokenSilently({
      audience: AUTH0_AUDIENCE,
      scope: "openid profile email",
    });
```
Even tho we have a token in the cache with the above scopes, it doesn't have the same audience. This means our SDK can not use those tokens and needs to request a new set of token, which will happen in an non-interactive way (iframe) which only works on safari (and any browser blocking third party cookies) when using custom domains.

The idea here should be to either use custom domains, specify the audience on the AuthProvider or catch the LOGIN_REQUIRED error when calling `getAccessTokenSilently` and fallback to `loginWithRedirect`, specifying the same audience and scope.

**Comment by mirshko** [comment]
Ahh okay word, that makes sense then, the documentation around this should be improved as its quite confusing.

I removed our usage of different audiences so I can now set this on the AuthProvider and use those refresh tokens and solve this issue. 

Im guessing that resolves this issue then! 

Thanks for all the help!

**Comment by mirshko** [comment]
Quick question, is the `offline_access` scope required for the use of the refresh tokens? 

We we're using this to enable refresh tokens when using nextjs-auth0 and having issues where the accessToken would expire but the user's session did not yet. 

I assume I can remove this offline_access scope now from the scope grant?

**Comment by frederikprijck** [comment]
The scope is required to use Refresh Tokens. However, our SDK adds it for you if needed when u set useRefreshTokens to true: https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L280-L282

So you should be fine to omit it in your code.

**Comment by mirshko** [comment]
Okay word! Thanks!

**Comment by frederikprijck** [comment]
Closing this, but let me know if you need additional info.
