### ISSUE TITLE
Redirect loop in debug builds using `StrictMode` with React 18.0.0-rc.0

### ISSUE THREAD

**Issue by peterhirn** [auth0/auth0-react#310]
### Describe the problem
I experience a redirect loop using `withAuthenticationRequired` with React v18 (rc) in debug builds with `webpack-dev-server` when `StrictMode` is enabled. Everything works fine in production builds (`webpack-dev-server` not involved) or when disabling `StrictMode`.

My implementation is very similar to https://auth0.com/blog/complete-guide-to-react-user-authentication/ with minimal adjustments for react-router v6.

I reckon this is related to `StrictMode` changes in v18 (was mentioned at React Conf 2021).
 
### Environment

```
"@auth0/auth0-react": "^1.8.0"
"react": "^18.0.0-rc.0"
"react-router-dom": "^6.2.1"
"webpack-dev-server": "^4.7.0"
```

**Comment by adamjmcgrath** [comment]
Hi @peterhirn - we don't currently support react 18, but thanks for the heads up

I updated the example app to react 18 and couldn't reproduce the issue you've described - but happy to debug a reproducible example if you can provide one.

There is an issue with [Strict Effects](https://github.com/reactwg/react-18/discussions/19) and `withAuthenticationRequired` which is causing `loginWithRedirect` to be called twice (because when strict effects are enabled, React intentionally double-invokes effects) which we will have to address when v18 is released and we add support for it.

**Comment by peterhirn** [comment]
Hi. Thanks for trying to reproduce, might be some other issue in my app. I'll try to create a minimal example.

**Comment by adamjmcgrath** [comment]
Thanks @peterhirn - if you create an example the reproduces the issue, let me know and I'll reopen this
