### ISSUE TITLE
Question about XSS and the getAccessTokenSilently func

### ISSUE THREAD

**Issue by OriAmir** [auth0/auth0-react#313]
hi, if I understand right oauth0 storing the access token in the browser memory(not sure what it's exactly mean) and we can get the token using `getAccessTokenSilently` func.
now, it looks like the attacker could easily inject script and get the token using the `getAccessTokenSilently` func.

I also read the whole article about `xss` here:https://auth0.com/blog/cross-site-scripting-xss/ but I don't see any reall solution from oauth0 side.
the q if it's my responsibility to take care of that and oauth0 not a responsibility to that? or the only option toa void xss is to use httponly cookie(diff approach).

thanks!

**Comment by adamjmcgrath** [comment]
Hi @OriAmir - thanks for your question

> the q if it's my responsibility to take care of that and oauth0 not a responsibility to that? 

Using the SPA approach for authentication and storing the user's tokens in the browser inherently puts them at risk of XSS - all the SDK can do is provide helpful methods, like `getAccessTokenSilently` to make it easier for the developer to do SPA authentication.

It can't remove the risk of the SPA approach from XSS, this approach inherently makes tokens directly accessible to the browser, so it's the application developers job to make sure their SPA is not vulnerable.

The React SDK should not of course introduce any XSS, or other, vulnerabilities but it can't prevent you from writing vulnerable code in your application.

> or the only option toa void xss is to use httponly cookie(diff approach).

Using the Regular Web Application approach (as opposed to the SPA approach) mitigates the issue of XSS because the user's tokens are only available to the server by default.

Have a look at this example, which uses the Regular Web Application approach with a SPA https://auth0.com/docs/login/spa-authenticate-with-cookies

**Comment by adamjmcgrath** [comment]
Closing - feel free to ping me if you want to reopen
