### ISSUE TITLE
Flexibility issue refered to path used to get tokens

### ISSUE THREAD

**Issue by paluchi** [auth0/auth0-react#361]
I need to use 'https://<my_cognito_url>/oauth2/token', but seems that reach '/oauth2/token' can't be achieved with this library.

'/oauth/token' is the one and only path you can use, providers like, which have custom paths, have not compatibility with this library

![image (1)](https://user-images.githubusercontent.com/26327672/167488020-eb53ce0d-2350-4000-804b-1e7da2ef9493.png)

**Comment by frederikprijck** [comment]
Thanks for reaching out. Our React SDK is intended to be used with Auth0, not with other Identity Providers. This is mostly because we have some things inside the SDK that are specific to Auth0 and might cause problems with other Identity Providers, the URL you are mentioning is one of those things.

Therefor there are no plans to make this URL configurable.
