### ISSUE TITLE
Invalid state error returned instead of unauthorized error

### ISSUE THREAD

**Issue by weisssean** [auth0/auth0-react#365]
- SDK Version: 1.10.1
- React Platform Version:17.0.0

When getting this redirect that that I set up with rules I get **"invalid state"** as the error instead of the actual error returned.

The redirected URL:
http://<My Domain>/?error=unauthorized&error_description=Please%20verify%20your%20email%20before%20logging%20in.&state=QnFTa0JoRnJscDZPcklwTWdrbnM3OThMUDh6ODZ2YXlpRHZtUWhzLWhUcw%3D%3D#/

in const { isAuthenticated, error, logout } = useAuth0() the error is **invalid state** instead of the expected **unauthorized**.

**Comment by adamjmcgrath** [comment]
Hi @weisssean - thanks for raising this

This is expected behaviour, the client [checks for the state](https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L674) (to confirm that the login was initiated from the application) before asserting any errors from the AS [here](https://github.com/auth0/auth0-spa-js/blob/master/src/Auth0Client.ts#L680)

Which makes sense, since if the client can't establish that the login started from the app, then it can't confirm that the messages from the server are for it

**Comment by weisssean** [comment]
So how do I get and show the correct error to the user? scrape it from the URL? seems broken to me.
![Screen Shot 2022-05-25 at 8 47 14 AM](https://user-images.githubusercontent.com/726748/170265835-304ba236-93a3-4f99-8160-1d6505a1e443.png)

**Comment by adamjmcgrath** [comment]
Are you hitting that URL as part of a login flow? If so, then your login flow is broken, because the SDK cannot pick up the state cookie to verify the callback request.

If you're just hitting that URL out of the context of a login flow, then I don't see why you want to show that message to the user. You're just creating a route that shows the user whatever you put in the error parameter.

**Comment by weisssean** [comment]
OK, my issue was just that I had an error already in the url and I refresh the page. Instead of that error being in the useAuth0 ().error, it returns that "invalid state" error.
Not the expected behavior but I can live with that.

Thank you @adamjmcgrath
