### ISSUE TITLE
400 on /authorize should result in error being set and/or loading being false

### ISSUE THREAD

**Issue by tfmark** [auth0/auth0-react#415]
### Describe the problem you'd like to have solved

In the screenshot below I have loaded our landing page, auth0 is silently trying to hit <auth0_tenant>/authorize and is getting a 400 back. `isAuthenticated` is false, `isLoading` is true, error is undefined, so I should just sit and wait for auth0 to do something...

![image](https://user-images.githubusercontent.com/80677094/194261097-916aabbf-e675-47a0-a72b-b31ae4a480cc.png)

Once the internal auth0 timeout eventually triggers (60s? 120s? I forget), `isLoading` is set to false / and `error` is set to Timeout.

I can then happily show my user a login page, but the user has probably gotten bored and closed the tab by that point.

### Describe the ideal solution

User should not be sat at our loading screen waiting for auth0's timeout to trigger

## Alternatives and current work-arounds

Don't show user a loading page whilst auth0 is loading...

## Screenshot from Network tab

![image](https://user-images.githubusercontent.com/80677094/194262405-326019da-3d4e-4b54-a9bd-49f01f72fd45.png)

**Comment by adamjmcgrath** [comment]
Hi @tfmark - thanks for raising this.

Unfortunately, there's no way for the browser window to know what the status (or the content) of the `/authorize` page is. All the SDK can do is listen for an event from the other window and timeout if it doesn't get one.

> I can then happily show my user a login page, but the user has probably gotten bored and closed the tab by that point.

You should only get this when the client is incorrectly configured, so this should only happen during development.

**Comment by tfmark** [comment]
Thanks for the swift reply @adamjmcgrath - is it possible to tweak the timeout (to e.g. 5 seconds)? We are seeing clients sat on the Loading page until the timeout is hit - it's not just something that is happening in dev, so would be nice to only have them sat for a few seconds rather than a minute+.

**Comment by adamjmcgrath** [comment]
You can use [`authorizeTimeoutInSeconds`](https://auth0.github.io/auth0-spa-js/interfaces/auth0clientoptions.html#authorizetimeoutinseconds)

But you shouldn't be getting 400s with a correctly configured client - you [tenant logs](https://auth0.com/docs/deploy-monitor/logs/view-log-events) should tell you what the issue is and you should be able to resolve it in code.

**Comment by tfmark** [comment]
Aha, am seeing `Failed Silent Auth` (The specified redirect_uri 'https://<snip>.tradefeedr.com' does not have a registered origin.). I guess that is related to having `useRefreshTokens={true}` so gonna deploy that change and check in the morning once my token has expired.

Failing that I'll *also* set a timeout to 5 seconds 👍 - will report back tomorrow and hopefully close out this ticket.

**Comment by Alvaro948P4Q** [comment]
Hi @adamjmcgrath ,

Thanks for your anwser, had the same problem and setting `useRefreshTokensFallback: false` fixed the issue.

In my particular case, this was a capacitor / angular application with refresh tokens enabled.

https://community.auth0.com/t/auth0-app-id-doesnt-link-with-the-android-application/67288/4

The problem here is that the auth0 logs is telling to add "<app_id>://<domain>/capacitor/<app_id>/callback" as an Allowed origin, which leads to a much dificult error.
