### ISSUE TITLE
I can not send audience with getAccessTokenSilently when refresh token

### ISSUE THREAD

**Issue by Kency1013** [auth0/auth0-react#421]
Hi everyone,
I use 
`
const token = await getAccessTokenSilently({
        audience: 'http://localhost:3000',
        test: '1234',
      });
`
but I not see 'audience' in request
![image](https://user-images.githubusercontent.com/32979458/197169903-a49f5416-e9f7-4755-87f0-6e57c31e2229.png)

**Comment by adamjmcgrath** [comment]
Hi @Kency1013 - thanks for raising this.

The refresh grant doesn't accept an audience parameter (see https://auth0.com/docs/api/authentication#refresh-token), you can only refresh a token for an audience you have logged in with.

`getAccessTokenSilently` supports that parameter because you can send the audience when attempting to login silently using iframes (which this SDK also supports when you're not using RTs)
