### ISSUE TITLE
Access token updated after account linking

### ISSUE THREAD

**Issue by marcovdijk** [auth0/auth0-react#425]
### Describe the problem

After linking a social login provider (e.g. google-oauth2) to a user-password regular account the subject of the token is changed to the `google-oauth2` id is instead of the original `auth0` id. 

### What was the expected behavior?

We expect the subject to stay `auth0` and not change to the linked google account.

### Reproduction

```
  const linkAccount = useCallback(
    async (provider: string) => {
      const token = await getAccessToken();

      await loginWithPopup({ max_age: 0, connection: provider });
      const { __raw: socialLoginToken } = await (getIdTokenClaims() as Promise<IdToken>);

      AuthServiceNew.linkAccount(provider, socialLoginToken, { Authorization: `Bearer ${token}` });
    },
    [getAccessToken, getIdTokenClaims, loginWithPopup]
  );
```

The service basically uses the Management API to connect the accounts.

### Environment

- **Version of `auth0-react` used: 1.12.0**
- **Which browsers have you tested in?: Chrome**

**Comment by ewanharris** [comment]
Hey @marcovdijk 👋🏻 

That's happening because calling `loginWithPopup` is making the account you're linking the now logged in user in the application.

We recently added support for what you're trying to achieve by adding support for multiple Auth0Providers in a single application (#416) by passing a [React context](https://auth0.github.io/auth0-react/interfaces/Auth0ProviderOptions.html#context) as part of the provider configuration and then using this when calling `useAuth0`. 

This would allow you to have a main provider and a linked account provider with separate contexts so that your main user does not get overwritten, you can check out a React version of the [account linking sample](https://github.com/auth0-samples/auth0-link-accounts-sample/tree/react-variant/React) for how to achieve this.

The main pieces are the [Provider configuration](https://github.com/auth0-samples/auth0-link-accounts-sample/blob/react-variant/React/src/index.js#L25-L51) and then calling `useAuth0` with the [context associated with your linking provider](https://github.com/auth0-samples/auth0-link-accounts-sample/blob/react-variant/React/src/components/LinkedAccounts.js#L20).

**Comment by marcovdijk** [comment]
Thanks for the reply @ewanharris! I think this is exactly what I need. I will keep you posted.

**Comment by adamjmcgrath** [comment]
Thanks @ewanharris and @marcovdijk - closing as I believe we've answered your question. feel free to ping us if you need any more assistance

**Comment by marcovdijk** [comment]
Worked like a charm 👍

**Comment by zachgoll** [comment]
@ewanharris know this issue is closed, but mind me asking, are there plans to add the React example app to the `master` branch of [this repo](https://github.com/auth0-samples/auth0-link-accounts-sample)?

I think either adding this example to the `master` branch or a link to the `react-variant` branch added to the [Auth0 docs here](https://auth0.com/docs/manage-users/user-accounts/user-account-linking/user-initiated-account-linking-client-side-implementation) would be super helpful to future Auth0 customers 😃
