### ISSUE TITLE
useApi Hook in Your Examples Does Not Show Any Code

### ISSUE THREAD

**Issue by Bilbosax** [auth0/auth0-react#499]
I am having a lot of issues successfully creating a useApi hook so I came to your documentation to find out more about it.  In your examples at the link below, you have a specific link that says "**Create a useApi hook for accessing protected APIs with an access token**", but when you click on it it does not take you anywhere, does not display any code, or discuss creating a useApi hook.  It is an empty link.  Any chance you guys could fill in that section soon?

https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md

We are working on this issue over on the community forums at this link if you want to chime in:

https://community.auth0.com/t/how-to-create-a-useapi-hook/99931

**Comment by adamjmcgrath** [comment]
Hi @Bilbosax - thanks for raising this

We used to have an example for that, but we removed that because there's lots of great libraries and resources for how to call APIs with react, eg 

Examples of writing your own:
- https://andrewstevens.dev/posts/useApi-react-hook/
- https://www.f80.dev/posts/the-useapi-hook
- https://dev.to/shaedrizwan/building-custom-hooks-in-react-to-fetch-data-4ig6

Libraries:
- https://react-query-v3.tanstack.com/
- https://swr.vercel.app/

And we felt it's out of scope for an authentication api to teach you how to do data fetching in react.

I'll remove that table of contents item as it shouldn't be there.

Also, If you want to look at the old docs, you can see what it used to be here https://github.com/auth0/auth0-react/blob/v1.12.1/EXAMPLES.md#create-a-useapi-hook-for-accessing-protected-apis-with-an-access-token
