### ISSUE TITLE
openUrl requires a returned promise, but why?

### ISSUE THREAD

**Issue by eddiemonge** [auth0/auth0-react#521]
### Describe the problem

In version 2.x.x, why does `openUrl` as a function, require a returned promise? The example shows it returning `void`, which doesn't need to be resolved in a promise.
```
* @example
   * await auth0.logout({
   *   async openUrl(url) {
   *     window.location.replace(url);
   *   }
   * });
   */
  openUrl?: false | ((url: string) => Promise<void>);
```

**Comment by frederikprijck** [comment]
Hello,

This is because some inegrations will return a promise, such as Capacitor's [Browser.open](https://capacitorjs.com/docs/apis/browser#open).

Typically, opening a browser is an async operation, but not when using window.location.replace.
However, when you take control over opening the URL, our SDK will wait until the returned promise is resolved.

**Comment by eddiemonge** [comment]
I meant the example does not need to be an async function since it returns void. By changing the type to 
```
openUrl?: false | ((url: string) => Promise<void> | void)
```
and then the implementation to support that (which might be as simple as `openUrl === false || Promise.resolve(openUrl)`, it would make the consumer's leaves slightly easier since they can do a normal callback or a promise based callback.

**Comment by eddiemonge** [comment]
Thank you all!
