### ISSUE TITLE
Auth0 hidden "Continue" button ? Why?

### ISSUE THREAD

**Issue by DenisCor** [auth0/auth0-react#539]
### Checklist

- [X] The issue can be reproduced in the [auth0-react sample app](https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Auth0 has a hidden "Continue" button class="ulp-button-bar-hidden" aria-hidden:true". Whats its purpose? our Cypress Tests are failing because it spots another "Continue" button..
![777](https://github.com/auth0/auth0-react/assets/62544827/01537925-7b70-4287-9a82-9ab52eda4b8a)

### Reproduction

inspect dom

### auth0-react version

1.10.2

### React version

17.0.2

### Which browsers have you tested in?

Chrome, Firefox

**Comment by frederikprijck** [comment]
Thanks for reaching out.

Our SDK has no control over the HTML being rendered on auth0's login page, so I can not tell you why there is a hidden continue button.

Closing, as there isn't something we can do about that from our SDK.

**Comment by DenisCor** [comment]
no explanation whatsoever.. can you at least point me in the right direction?

**Comment by frederikprijck** [comment]
At the SDK side, we do not work on the login page and are not aware on why they would add that.

You can provide [product feedback](https://auth0.com/feedback) if you believe there is something wrong.

But in general, I would recommend updating your Cypress tests to consider for the hidden button.

You can look at our Cypress tests for our Next SDK: https://github.com/auth0/nextjs-auth0/blob/main/cypress/e2e/smoke.cy.ts#L9-L13 (our React SDK is using the classic login page, so that is a bit different)
