### ISSUE TITLE
Supporting rememberLastLogin option

### ISSUE THREAD

**Issue by jhebb** [auth0/auth0-react#80]
### Describe the problem you'd like to have solved

Hi, I'm wondering if this library will support the `rememberLastLogin` option from some of the other SDKs (https://auth0.com/docs/libraries/lock/v11/configuration#rememberlastlogin-boolean-) as we've lost this feature switching over to the hooks-based solution.

### Describe the ideal solution

The `rememberLastLogin` setting is supported via the React SDK

## Alternatives and current work-arounds

 I've tried adding this to https://auth0.github.io/auth0-react/interfaces/withauthenticationrequiredoptions.html#loginoptions even though the option isn't listed but doesn't seem to be implemented

**Comment by adamjmcgrath** [comment]
Hi @jhebb - looking at https://auth0.com/docs/libraries/lock/v11/configuration#rememberlastlogin-boolean-

"New tenants automatically have Seamless SSO enabled. With this enabled, the `rememberLastLogin` option will not be relevant because if there is a session in place then the hosted login page will not be displayed at all. Using Seamless SSO is highly recommended because it provides a seamless authentication experience: users log in once and won’t have to enter credentials again when they navigate either through the applications you have built, or third party apps. If the user is not logged in they will be redirected to the login screen, as expected."

Instructions on how to check the Seamless SSO setting in your tenant: https://auth0.com/docs/dashboard/guides/tenants/enable-sso-tenant

**Comment by jhebb** [comment]
Hi @adamjmcgrath - thanks for the reply.

Maybe I'm misunderstanding how the `rememberLastLogin` feature works - enabling Seamless SSO doesn't seem to make a difference, but i'm testing by explicitly logging my user out via the `logout` action in `useAuth0()` so perhaps Auth0 doesn't try to remember your user in that situation?

**Comment by adamjmcgrath** [comment]
Hi @jhebb by default `logout` will log you out of your Auth0 session too. You can do `logout({ localOnly: true })`to prevent this https://auth0.github.io/auth0-react/interfaces/logoutoptions.html#localonly

But beware, we have a known issue with `localOnly` #72 so you'd need to do something like `logout({ localOnly: true }); window.location.reload()` as a workaround before we fix it

**Comment by jhebb** [comment]
If I leave Seamless SSO off and use `localOnly: true`, then I get the behaviour we had from before, but reading the docs you provided I see that maybe this isn't the experience we want so I'll re-assess our goals first.

Thanks for the info, and feel free to close since this behavior already exists!

**Comment by adamjmcgrath** [comment]
Will do - thanks @jhebb
